Name:           westonite
Version:        14.0.1
Release:        2%{?dist}
Summary:        Standalone Weston-based Wayland compositor

# Vendored weston sources; see VENDOR.md
License:        MIT
URL:            https://github.com/nhwalker/example-weston-standalone
Source0:        %{name}-%{version}.tar.gz
# Vendored cargo registry dependencies (generated by scripts/rpm-build.sh
# with `cargo vendor`, plan §6): the %%build cargo run is offline.
Source1:        %{name}-vendor-%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  meson >= 0.63
# Rust shell plugin (R1+, docs/rust-migration-plan.md §7): the shipping
# desktop-shell.so is the westonite-shell-plugin cdylib; the meson-built
# C shell stays in-tree as the behavioral oracle but is not packaged.
BuildRequires:  cargo
BuildRequires:  rust
BuildRequires:  pkgconfig(libweston-14) >= 14.0.1
BuildRequires:  pkgconfig(wayland-server)
BuildRequires:  pkgconfig(wayland-scanner)
BuildRequires:  pkgconfig(wayland-protocols) >= 1.33
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(libevdev)
BuildRequires:  pkgconfig(pixman-1)
# Enables HAVE_XWAYLAND_LISTENFD; the build works without it
BuildRequires:  pkgconfig(xwayland)

# libweston runtime, backends, renderers and xwayland.so (EPEL 10)
Requires:       weston-libs%{?_isa} >= 14.0.1
Recommends:     xorg-x11-server-Xwayland

%description
Westonite is the Weston 14 compositor frontend and desktop-shell plugin,
built standalone against the distribution's libweston 14 packages and
renamed so it installs alongside the stock weston package. It ships no
helper clients: there is no panel or on-screen keyboard unless configured
to use external ones (see westonite.ini.example).

%prep
%autosetup
# Unpack the vendored crates and point cargo at them (offline build).
tar -xzf %{SOURCE1}
mkdir -p .cargo
cat > .cargo/config.toml <<'EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

%build
%meson
%meson_build
cargo build --release --offline --locked -p westonite-shell-plugin

%install
%meson_install
# R1+ (plan §7): the Rust plugin replaces the meson-installed C shell as
# the shipping desktop-shell.so — same replacement rust-shell-install.sh
# performs in the CI containers, now applied to the packaged artifact.
install -m 755 target/release/libwestonite_shell_plugin.so \
        %{buildroot}%{_libdir}/westonite/desktop-shell.so

%files
%license COPYING
%doc VENDOR.md
%{_bindir}/westonite
%dir %{_libdir}/westonite
%{_libdir}/westonite/desktop-shell.so
%{_libdir}/westonite/libexec_westonite.so
%{_libdir}/westonite/libexec_westonite.so.*
%{_datadir}/wayland-sessions/westonite.desktop
%{_datadir}/doc/westonite/westonite.ini.example

%changelog
* Sun Jul 26 2026 Nathan Walker <nathan.h.walker@gmail.com> - 14.0.1-2
- Ship the Rust desktop-shell plugin (westonite-shell-plugin) as
  desktop-shell.so; cargo deps vendored via Source1 for offline %%build.

* Tue Jul 21 2026 Nathan Walker <nathan.h.walker@gmail.com> - 14.0.1-1
- Initial package: weston 14.0.1 frontend + desktop-shell built against
  EPEL 10 libweston-14 (weston-libs), renamed to westonite, no helper
  clients, Xwayland enabled.
