//! UNSAFE: raw FFI surface for libweston 14 (installed EPEL RPM headers).
//!
//! Nothing in this crate is safe to call; it exists so that exactly two
//! crates — `weston` (the fence) and, later, `westonite-spawn` — can reach
//! C.  The safe crates must never depend on this crate (plan §2, enforced
//! by the CI dependency-graph check).
//!
//! `src/bindings.rs` is committed, generated by `scripts/regen-bindings.sh`
//! inside the build container (D5); `build.rs` enforces that the installed
//! libweston version still matches the one the bindings were generated
//! from.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unsafe_op_in_unsafe_fn)] // bindgen output predates the lint
#![allow(clippy::all)]

#[rustfmt::skip] // generated file — must stay byte-identical to the regen script's output
mod bindings;
pub use bindings::*;

/// The Xwayland listen-socket flag (C frontend xwayland.c LISTEN_STR):
/// `-listenfd` when the build-time xwayland.pc advertises
/// `have_listenfd`, the deprecated `-listen` spelling otherwise —
/// build.rs runs the same probe as the C meson.build.
pub const XWAYLAND_LISTEN_ARG: &str = match env!("WSYS_XWAYLAND_LISTENFD").as_bytes() {
    [b'1'] => "-listenfd",
    _ => "-listen",
};
