/* bindgen input for weston-sys (regenerated by scripts/regen-bindings.sh).
 *
 * Everything here must come from the *installed* EPEL 10 weston-devel
 * 14.0.1 headers (or wayland-devel / pixman headers they pull in) — never
 * from the reference weston tree.  The §3a header-fact verification and
 * the pkg-config version tripwire in build.rs are keyed to these headers.
 */

#include <wayland-server-core.h>

#include <libweston/libweston.h>
#include <libweston/desktop.h>
#include <libweston/shell-utils.h>
#include <libweston/weston-log.h>
#include <libweston/windowed-output-api.h>
#include <libweston/version.h>
#include <libweston/xwayland-api.h>

#include <libweston/backend-drm.h>
#include <libweston/backend-headless.h>
#include <libweston/backend-pipewire.h>
#include <libweston/backend-rdp.h>
#include <libweston/backend-vnc.h>
#include <libweston/backend-wayland.h>
#include <libweston/backend-x11.h>

#include "shim/shim.h"
#include "shim/testsupport.h"
