#!/bin/sh
# Regenerate crates/weston-sys/src/bindings.rs from the *installed*
# libweston 14 headers (plan §6, D5).  Run inside the build container:
#
#   docker run --rm -v "$PWD":/src westonite-build /src/scripts/regen-bindings.sh
#
# The output is committed; build.rs asserts the recorded libweston version
# still matches pkg-config at every build (the R-C tripwire).  Re-run this
# script — and re-verify the §3 header facts — whenever EPEL bumps weston.
#
# REGEN_BINDINGS_OUT=<path> writes there instead of the committed file
# (used by rust-fence-check.sh to diff without touching the tree).
set -eu

cd "$(dirname "$0")/.."
SYS=crates/weston-sys
OUT="${REGEN_BINDINGS_OUT:-$SYS/src/bindings.rs}"

# Pinned: the committed output embeds the bindgen version, so an unpinned
# tool would make header drift indistinguishable from tool drift.  Bump
# this and regenerate in one commit when moving to a newer bindgen.
BINDGEN_VERSION=0.72.1

command -v bindgen >/dev/null 2>&1 || {
    echo "bindgen CLI not found; installing with cargo (needs network)..." >&2
    cargo install bindgen-cli --version "$BINDGEN_VERSION" --locked
    PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"
}

ACTUAL=$(bindgen --version)
[ "$ACTUAL" = "bindgen $BINDGEN_VERSION" ] || {
    echo "bindgen version mismatch: have '$ACTUAL', need 'bindgen $BINDGEN_VERSION'" >&2
    echo "(install with: cargo install bindgen-cli --version $BINDGEN_VERSION --locked)" >&2
    exit 1
}

MODVERSION=$(pkg-config --modversion libweston-14)
CFLAGS=$(pkg-config --cflags libweston-14 wayland-server pixman-1)

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

bindgen "$SYS/wrapper.h" \
    --allowlist-item 'wl_.*' \
    --allowlist-item 'WL_.*' \
    --allowlist-item 'weston.*|WESTON.*' \
    --allowlist-item 'wet_.*' \
    --allowlist-item 'wsys_.*' \
    --allowlist-item 'pixman_.*' \
    --allowlist-item 'xkb_.*' \
    --blocklist-function 'weston_vlog.*' \
    --blocklist-function 'weston_log_scope_vprintf' \
    --blocklist-function 'weston_log_set_handler' \
    --blocklist-function 'wl_resource_post_error_vargs' \
    --no-doc-comments \
    --default-enum-style=moduleconsts \
    --no-prepend-enum-name \
    -o "$TMP" \
    -- $CFLAGS -I"$SYS" \
    "-DARRAY_LENGTH(a)=(sizeof (a) / sizeof (a)[0])"
# ^ windowed-output-api.h's static inline uses weston's internal
#   ARRAY_LENGTH helper macro, which the RPM does not install; supply it
#   so the installed headers parse standalone.

{
    echo "// @generated by scripts/regen-bindings.sh — do not edit."
    echo "// libweston-modversion: $MODVERSION"
    echo "// bindgen: $ACTUAL"
    cat "$TMP"
} > "$OUT"

echo "wrote $OUT (libweston $MODVERSION)"
