#!/bin/sh
# Regenerate crates/weston-sys/src/bindings.rs from the *installed*
# libweston 14 headers (plan §6, D5).  Run inside the build container:
#
#   docker run --rm -v "$PWD":/src westonite-build /src/scripts/regen-bindings.sh
#
# The output is committed; build.rs asserts the recorded libweston version
# still matches pkg-config at every build (the R-C tripwire).  Re-run this
# script — and re-verify the §3 header facts — whenever EPEL bumps weston.
set -eu

cd "$(dirname "$0")/.."
SYS=crates/weston-sys

command -v bindgen >/dev/null 2>&1 || {
    echo "bindgen CLI not found; installing with cargo (needs network)..." >&2
    cargo install bindgen-cli --locked
    PATH="$HOME/.cargo/bin:$PATH"
}

MODVERSION=$(pkg-config --modversion libweston-14)
CFLAGS=$(pkg-config --cflags libweston-14 wayland-server pixman-1)

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

bindgen "$SYS/wrapper.h" \
    --allowlist-item 'wl_.*' \
    --allowlist-item 'WL_.*' \
    --allowlist-item 'weston.*|WESTON.*' \
    --allowlist-item 'wet_.*' \
    --allowlist-item 'wsys_.*' \
    --allowlist-item 'pixman_.*' \
    --allowlist-item 'xkb_.*' \
    --blocklist-function 'weston_vlog.*' \
    --blocklist-function 'weston_log_scope_vprintf' \
    --blocklist-function 'weston_log_set_handler' \
    --blocklist-function 'wl_resource_post_error_vargs' \
    --no-doc-comments \
    --default-enum-style=moduleconsts \
    --no-prepend-enum-name \
    -o "$TMP" \
    -- $CFLAGS -I"$SYS" \
    "-DARRAY_LENGTH(a)=(sizeof (a) / sizeof (a)[0])"
# ^ windowed-output-api.h's static inline uses weston's internal
#   ARRAY_LENGTH helper macro, which the RPM does not install; supply it
#   so the installed headers parse standalone.

{
    echo "// @generated by scripts/regen-bindings.sh — do not edit."
    echo "// libweston-modversion: $MODVERSION"
    echo "// bindgen: $(bindgen --version)"
    cat "$TMP"
} > "$SYS/src/bindings.rs"

echo "wrote $SYS/src/bindings.rs (libweston $MODVERSION)"
